# Generated by Django 4.2.7 on 2023-12-04 19:57

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('duty', models.FloatField(max_length=256)),
                ('date_of_chenge', models.DateField()),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='chain.chain')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='продукты', to='chain.product', verbose_name='продукт')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
